name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Dar permisos de ejecución al gradlew
      run: chmod +x ./gradlew

    - name: Build JAR with Gradle
      run: ./gradlew clean build

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devopspvm:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devopspvm:latest
